export const siteConfig = {
  name: 'FreeTyper',
  title: 'FreeTyper — Type Faster. Free Forever.',
  description:
    'Master touch typing with free lessons, speed tests, and games. Track your WPM, crush your weak keys, and watch yourself improve — no signup, progress stays in your browser.',
  url: 'https://freetyper.com',
  author: 'Ashiqur Rahman',
  keywords: [
    'typing test',
    'typing speed test',
    'wpm test',
    'typing practice',
    'typing lessons',
    'touch typing',
    'free typing',
    'typing games',
    'keyboard practice',
    'typing speed',
    'words per minute',
    'typing tutor',
    'learn to type',
    'typing accuracy',
    'no login',
    'privacy-first',
  ],
  links: {
    github: 'https://github.com/ashiqur0202/freetyper',
  },
  adsenseClient: 'ca-pub-3237588309372777',
} as const;
